// The same thirteen entries as the timeline section in index.html, as data so
// the scene can lay them out. Keep both languages in step with that section.
//
// kind: 'shot' is a screenshot of the thing itself; 'mark' is an institution's
// own logo, which needs a light plate and clear space rather than a bleed.

export const entries = [
  {
    year: '2012–13',
    title: 'MIRAGE',
    ko: '안드로이드 커스텀 ROM',
    en: 'Android custom ROM',
    kind: 'shot',
    img: 'deck-232ebf/e7b7069ae8c7f14c9ca3dbbecbd7d8cf.png',
  },
  {
    year: '2017.03',
    titleKo: '아주대학교',
    titleEn: 'Ajou University',
    ko: '컴퓨터공학과 입학',
    en: 'computer engineering, enrolled',
    kind: 'mark',
    img: 'img/ajou-logo.png',
    imgKo: 'img/ajou-logo-ko.png',
  },
  {
    year: '2020.12',
    title: 'AjouBot',
    ko: '아주대 카카오톡 챗봇. 2022.12까지 2년 운영',
    en: 'KakaoTalk bot for Ajou University, in service until 2022.12',
    kind: 'shot',
    img: 'deck-232ebf/cca6f7307a2413ce60553dedb86a9b9e.png',
  },
  {
    year: '2022.04',
    title: 'KakaoPI',
    ko: '카카오톡으로 라즈베리파이 제어 (C, Python, Rust)',
    en: 'Raspberry Pi over KakaoTalk (C, Python, Rust)',
    kind: 'shot',
    img: 'deck-232ebf/6cfba1b07523c485654b76fe6ecc474e.png',
  },
  {
    year: '2022.04',
    title: 'AjouLibra',
    ko: '아주대 도서 검색·추천 (Rust, WASM, React)',
    en: 'Ajou library search and recommendation (Rust, WASM, React)',
    kind: 'shot',
    img: 'deck-232ebf/1f20e9dda6521aaf43f0bd2ddc402e00.png',
  },
  {
    year: '2022.11',
    title: 'DApp Lottery',
    ko: '이더리움 토큰 복권. 3인 팀, 토큰·서버·챗봇 담당',
    en: 'Ethereum token lottery. Team of three, owned token, server and chatbot',
    kind: 'shot',
    img: 'deck-232ebf/5fc9f34417934715d55e229445206c4e.gif',
  },
  {
    year: '2023.03',
    title: 'Hi-Rust',
    ko: 'Rust 입문 유튜브 튜토리얼',
    en: 'Rust tutorial series on YouTube',
    kind: 'shot',
    img: 'deck-232ebf/6d6c224b8d3a50bce4342a84274795dd.png',
  },
  {
    year: '2023.09',
    title: 'BeautyMinder',
    ko: '피부 타입 기반 화장품 관리 앱. 다섯 명 중 백엔드 리드, 2023.12까지',
    en: 'skin-type cosmetics app. Backend lead of five, through 2023.12',
    kind: 'shot',
    img: 'deck-232ebf/f5f7bd3affad4ab427c2959c7ca05ea0.png',
  },
  {
    year: '2024.02',
    titleKo: '아주대학교',
    titleEn: 'Ajou University',
    ko: '졸업',
    en: 'graduation',
    kind: 'mark',
    img: 'img/ajou-logo.png',
    imgKo: 'img/ajou-logo-ko.png',
  },
  {
    year: '2024.02 –',
    title: 'k-pullup',
    ko: '출시, 현재까지 운영',
    en: 'launches, still in service',
    kind: 'shot',
    img: 'portfolio/kpullup1.png',
  },
  {
    year: '2025.02',
    title: 'YTChatX',
    ko: 'YouTube 라이브 채팅 실시간 분석',
    en: 'real-time YouTube live-chat analysis',
    kind: 'shot',
    img: 'portfolio/ytchatx1.png',
  },
  {
    year: '2025.04',
    title: 'GoWave',
    ko: '코인 자동 매매 (Go), 2026.01까지',
    en: 'crypto autotrader in Go, through 2026.01',
    kind: 'shot',
    img: 'deck-232ebf/2631236a04abf0ea52ac3f197411e20e.png',
  },
  {
    year: '2025.09 –',
    title: 'LINE Plus',
    ko: 'DBaaS DevOps. 사내 프라이빗 클라우드의 관리형 DB. 현재 재직 중',
    en: 'DBaaS DevOps. Managed databases on a private cloud. Ongoing',
    kind: 'mark',
    img: 'img/line-app-icon.png',
  },
]
